# Etapa 1: Build
FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build-env
WORKDIR /app

# Copiar os arquivos de projeto (.csproj) para restaurar dependências
COPY src/CashFlow.Api/*.csproj ./CashFlow.Api/
COPY src/CashFlow.Application/*.csproj ./CashFlow.Application/
COPY src/CashFlow.Communication/*.csproj ./CashFlow.Communication/
COPY src/CashFlow.Domain/*.csproj ./CashFlow.Domain/
COPY src/CashFlow.Exception/*.csproj ./CashFlow.Exception/
COPY src/CashFlow.Infrastructure/*.csproj ./CashFlow.Infrastructure/

# Restaura as dependências
WORKDIR /app/CashFlow.Api
RUN dotnet restore

# Copia o restante do código para o container
WORKDIR /app
COPY src/ .

# Publica o projeto
WORKDIR /app/CashFlow.Api
RUN dotnet publish -c Release -o /app/out

# Etapa 2: Runtime
FROM mcr.microsoft.com/dotnet/aspnet:8.0
WORKDIR /app

# Copia os binários gerados na etapa anterior
COPY --from=build-env /app/out .

# Define o ponto de entrada
ENTRYPOINT ["dotnet", "CashFlow.Api.dll"]
